// Code generated by protoc-gen-go.
// source: supplier.proto
// DO NOT EDIT!

package northwind

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "artisan"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Supplier struct {
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ContactName  string `protobuf:"bytes,3,opt,name=contact_name,json=contactName" json:"contact_name,omitempty"`
	ContactTitle string `protobuf:"bytes,4,opt,name=contact_title,json=contactTitle" json:"contact_title,omitempty"`
	Address      string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	City         string `protobuf:"bytes,6,opt,name=city" json:"city,omitempty"`
	Region       string `protobuf:"bytes,7,opt,name=region" json:"region,omitempty"`
	PostalCode   string `protobuf:"bytes,8,opt,name=postal_code,json=postalCode" json:"postal_code,omitempty"`
	Country      string `protobuf:"bytes,9,opt,name=country" json:"country,omitempty"`
	Phone        string `protobuf:"bytes,10,opt,name=phone" json:"phone,omitempty"`
	Fax          string `protobuf:"bytes,11,opt,name=fax" json:"fax,omitempty"`
	Website      string `protobuf:"bytes,12,opt,name=website" json:"website,omitempty"`
	Email        string `protobuf:"bytes,13,opt,name=email" json:"email,omitempty"`
}

func (m *Supplier) Reset()                    { *m = Supplier{} }
func (m *Supplier) String() string            { return proto.CompactTextString(m) }
func (*Supplier) ProtoMessage()               {}
func (*Supplier) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *Supplier) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Supplier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Supplier) GetContactName() string {
	if m != nil {
		return m.ContactName
	}
	return ""
}

func (m *Supplier) GetContactTitle() string {
	if m != nil {
		return m.ContactTitle
	}
	return ""
}

func (m *Supplier) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Supplier) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Supplier) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Supplier) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Supplier) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Supplier) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Supplier) GetFax() string {
	if m != nil {
		return m.Fax
	}
	return ""
}

func (m *Supplier) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Supplier) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SupplierFK struct {
	// Types that are valid to be assigned to Supplier:
	//	*SupplierFK_Id
	//	*SupplierFK_Instance
	Supplier isSupplierFK_Supplier `protobuf_oneof:"supplier"`
}

func (m *SupplierFK) Reset()                    { *m = SupplierFK{} }
func (m *SupplierFK) String() string            { return proto.CompactTextString(m) }
func (*SupplierFK) ProtoMessage()               {}
func (*SupplierFK) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

type isSupplierFK_Supplier interface {
	isSupplierFK_Supplier()
}

type SupplierFK_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,oneof"`
}
type SupplierFK_Instance struct {
	Instance *Supplier `protobuf:"bytes,2,opt,name=instance,oneof"`
}

func (*SupplierFK_Id) isSupplierFK_Supplier()       {}
func (*SupplierFK_Instance) isSupplierFK_Supplier() {}

func (m *SupplierFK) GetSupplier() isSupplierFK_Supplier {
	if m != nil {
		return m.Supplier
	}
	return nil
}

func (m *SupplierFK) GetId() string {
	if x, ok := m.GetSupplier().(*SupplierFK_Id); ok {
		return x.Id
	}
	return ""
}

func (m *SupplierFK) GetInstance() *Supplier {
	if x, ok := m.GetSupplier().(*SupplierFK_Instance); ok {
		return x.Instance
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SupplierFK) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SupplierFK_OneofMarshaler, _SupplierFK_OneofUnmarshaler, _SupplierFK_OneofSizer, []interface{}{
		(*SupplierFK_Id)(nil),
		(*SupplierFK_Instance)(nil),
	}
}

func _SupplierFK_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SupplierFK)
	// supplier
	switch x := m.Supplier.(type) {
	case *SupplierFK_Id:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Id)
	case *SupplierFK_Instance:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Instance); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SupplierFK.Supplier has unexpected type %T", x)
	}
	return nil
}

func _SupplierFK_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SupplierFK)
	switch tag {
	case 1: // supplier.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Supplier = &SupplierFK_Id{x}
		return true, err
	case 2: // supplier.instance
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Supplier)
		err := b.DecodeMessage(msg)
		m.Supplier = &SupplierFK_Instance{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SupplierFK_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SupplierFK)
	// supplier
	switch x := m.Supplier.(type) {
	case *SupplierFK_Id:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Id)))
		n += len(x.Id)
	case *SupplierFK_Instance:
		s := proto.Size(x.Instance)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Supplier)(nil), "northwind.Supplier")
	proto.RegisterType((*SupplierFK)(nil), "northwind.SupplierFK")
}

func init() { proto.RegisterFile("supplier.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4d, 0x4e, 0xfb, 0x30,
	0x10, 0xc5, 0x9b, 0xf4, 0x2b, 0x9d, 0xb4, 0x7f, 0xfd, 0x65, 0xa0, 0x1a, 0x75, 0xc1, 0x47, 0xd9,
	0xb0, 0x2a, 0x02, 0x6e, 0x50, 0x24, 0x54, 0x09, 0x89, 0x45, 0x60, 0x8b, 0x2a, 0x37, 0x31, 0xd4,
	0x52, 0x6a, 0x47, 0xb6, 0xab, 0xd2, 0x1d, 0x97, 0x62, 0xcf, 0x92, 0x63, 0x70, 0x01, 0x56, 0x5c,
	0x00, 0xd9, 0x8e, 0x0b, 0xab, 0x78, 0x7e, 0xef, 0xcd, 0x8c, 0xf2, 0x06, 0xfe, 0xe9, 0x75, 0x55,
	0x95, 0x9c, 0xa9, 0x49, 0xa5, 0xa4, 0x91, 0xa4, 0x27, 0xa4, 0x32, 0xcb, 0x0d, 0x17, 0xc5, 0xe8,
	0x80, 0x2a, 0xc3, 0x35, 0x15, 0xe7, 0xf5, 0xd7, 0x3b, 0xc6, 0x5f, 0x31, 0x24, 0xf7, 0x75, 0x13,
	0xd9, 0x87, 0x98, 0x17, 0x18, 0x1d, 0x47, 0x67, 0xbd, 0x69, 0xeb, 0xf5, 0x0d, 0xa3, 0x2c, 0xe6,
	0x05, 0x21, 0xd0, 0x12, 0x74, 0xc5, 0x30, 0xb6, 0x3c, 0x73, 0x6f, 0x72, 0x02, 0xfd, 0x5c, 0x0a,
	0x43, 0x73, 0x33, 0x77, 0x5a, 0xd3, 0x69, 0x69, 0xcd, 0xee, 0xac, 0xe5, 0x14, 0x06, 0xc1, 0x62,
	0xb8, 0x29, 0x19, 0xb6, 0x9c, 0x27, 0xf4, 0x3d, 0x58, 0x46, 0x10, 0xba, 0xb4, 0x28, 0x14, 0xd3,
	0x1a, 0xdb, 0x4e, 0x0e, 0xa5, 0xdd, 0x9a, 0x73, 0xb3, 0xc5, 0x8e, 0xdf, 0x6a, 0xdf, 0x64, 0x08,
	0x1d, 0xc5, 0x9e, 0xb9, 0x14, 0xd8, 0x75, 0xb4, 0xae, 0xc8, 0x11, 0xa4, 0x95, 0xd4, 0x86, 0x96,
	0xf3, 0x5c, 0x16, 0x0c, 0x13, 0x27, 0x82, 0x47, 0xd7, 0xb2, 0x70, 0x6b, 0x72, 0xb9, 0x16, 0x46,
	0x6d, 0xb1, 0xe7, 0xd7, 0xd4, 0x25, 0x19, 0x41, 0xbb, 0x5a, 0x4a, 0xc1, 0x10, 0xfc, 0x5f, 0x7f,
	0x7e, 0x63, 0x94, 0x79, 0x44, 0x86, 0xd0, 0x7c, 0xa2, 0x2f, 0x98, 0xfe, 0x51, 0x2c, 0x20, 0x87,
	0xd0, 0xdd, 0xb0, 0x85, 0xe6, 0x86, 0x61, 0xdf, 0x6b, 0x1f, 0x56, 0x0b, 0xd0, 0xce, 0x64, 0x2b,
	0xca, 0x4b, 0x1c, 0x78, 0xf5, 0xdd, 0xcd, 0x74, 0x68, 0xfc, 0x08, 0x10, 0xe2, 0xbe, 0xb9, 0x25,
	0xff, 0x7f, 0x03, 0x9f, 0x35, 0x5c, 0xd8, 0x17, 0x90, 0x70, 0xa1, 0x0d, 0x15, 0xb9, 0x0f, 0x3c,
	0xbd, 0xdc, 0x9b, 0xec, 0x8e, 0x38, 0x09, 0xad, 0xb3, 0x46, 0xb6, 0xb3, 0x4d, 0x01, 0x92, 0x70,
	0xf6, 0x45, 0xc7, 0x5d, 0xf5, 0xea, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x03, 0x0b, 0xce, 0x09,
	0x02, 0x00, 0x00,
}
